# default configuration
baseURL = "https://www.lehighur.org"
languageCode = "en-us"
summaryLength = "10"
theme = "kross"
title = "Lehigh UR"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "style.css"

# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
name = "About Us"
hasChildren = true
weight = 1

[[menu.main]]
parent = "About Us"
name = "Our Story"
URL = "stories"

#[[menu.main]]
#parent = "About Us"
#name = "Our Members"
#URL = "members"

# regular menu
[[menu.main]]
name = "Projects"
weight = 1
hasChildren = true

[[menu.main]]
parent = "Projects"
name = "RoboSub 2022"
URL = "newest"

[[menu.main]]
parent = "Projects"
name = "Summer of 2021"
URL = "summer21"

#[[menu.main]]
#parent = "Projects"
#name = "RoboSub 2022"
#URL = "robosub22"

# regular menu
# [[menu.main]]
# name = "Media"
# weight = 1
# hasChildren = true

#[[menu.main]]
#parent = "Media"
#name = "Photos"
#URL = "photos"

#[[menu.main]]
#parent = "Media"
#name = "Videos"
#URL = "videos"

# regular menu
# [[menu.main]]
# name = "Reports"
# URL = "reports"
# weight = 1

# regular menu
[[menu.main]]
name = "Sponsors"
URL = "sponsors"
weight = 1

# regular menu
[[menu.main]]
name = "Contact Us"
URL = "contact"
weight = 10

# default parameters
[params]
home = "Home"
logo = "https://i.loli.net/2021/11/04/lhKN2m8zAIdsbPq.png"
# theme color
theme_color = "#41228e"
# contact info
phone = "N/A"
email = "inuwrobo@lehigh.edu"
address = "27 Memorial Dr W, Bethlehem, PA 18015"
# meta description
description = "Hi! We are Lehigh UR"
# google analytics
google_analytics_id = "" # Your ID
# baidu site verification
baidu_site_verification = "" #Your verification code
# baidu analytics
baidu_analytics_id = "" #Your ID
# copyright
copyright = "Copyright &copy; 2021 a Theme by [Gethugothemes](https://gethugothemes.com)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
# [[params.social]]
# icon = "ti-facebook"
# URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/lehighur/"

[[params.social]]
icon = "ti-github"
URL = "https://github.com/Lehigh-Underwater-Robotics"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/company/lehigh-underwater-robotics/"

